version: '3.1'

services:
  api:
    image: angelfym/student-api:1.2.4
    restart: always
    ports:
      - 8912:5000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: superootpassword

  db:
    image: postgres:9.6.16-alpine
    restart: always
    ports:
      - 7789:5432
    environment:
      POSTGRES_PASSWORD: superootpassword