version: "3"
services:
  api:
    image: dockerhubuser2020/api-student:13
    deploy:
      replicas: 1
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: SVZUdt7eP3X5Hysy
    ports:
      - 8080:5000
    networks:
      - api-tier

  web:
    image: dockerhubuser2020/web-student:13
    deploy:
      replicas: 1
    ports:
      - 80:80
    networks:
      - api-tier

networks:
  api-tier: